# Generated by Django 4.1 on 2022-09-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customer_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='braintree_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
