# Generated by Django 4.1 on 2022-09-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_customer_customer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.IntegerField(default=None, max_length=12),
        ),
    ]
