# Generated by Django 4.1 on 2022-09-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_address_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.IntegerField(default=None),
        ),
    ]
