# Generated by Django 4.1 on 2022-09-24 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('account', '0007_alter_customerorder_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='braintree_id',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='customer',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='customer_order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='account.customer'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='app.product'),
        ),
    ]
