# Generated by Django 4.1 on 2022-09-08 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='useraddress',
        ),
    ]
