# Generated by Django 4.1 on 2022-09-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_customer_braintree_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='paid',
        ),
        migrations.AddField(
            model_name='customer',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
