# Generated by Django 4.1 on 2022-09-08 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_address_customer_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='useraddress',
        ),
    ]
