# Generated by Django 4.1 on 2022-10-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='used',
            field=models.IntegerField(default=1),
        ),
    ]
