# Generated by Django 4.1 on 2022-09-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
